---
abstract: 'Generate functional signatures for Perl source code'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Copy: 0
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Signature
name: Perl-Signature
no_index:
  directory:
    - inc
    - t
requires:
  Config::Tiny: 2.00
  Digest::MD5: 2.30
  PPI: 1.109
  Storable: 2.11
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.09
