name: Perl-Signature
version: 0.05
abstract: Generate functional signatures for Perl source code
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  Storable: 2.11
  Digest::MD5: 2.30
  Config::Tiny: 2.00
  PPI: 0.990
no_index:
  directory:
    - t.data
    - inc
generated_by: Module::Install version 0.36
