
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.08
name: Perl-Signature
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  File::Copy: 0
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  PPI: 1.109
  perl: 5.005
  Digest::MD5: 2.30
  Storable: 2.11
  Config::Tiny: 2.00
abstract: Generate functional signatures for Perl source code
